services:
  nextjs:
    container_name: swipeerde_nextjs
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=http://localhost:8140
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: swipeerde_pocketbase
    restart: unless-stopped
    ports:
      - "8140:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
